### ISSUE TITLE
Seiya Suzuki isn't searchable

### ISSUE THREAD

**Issue by DaGoalieMan** [CaptainMoustache/basebot#11]
This is bizarre..  Seiya Suzuki exists and is having a good year.  Looking through your other tickets, I saw you talk about the stats API and then poked around MLB's API and found Seiya's Player ID (673548).  He shows on the 40 man roster for Chicago.  But if you search his name through Basebot, you don't get a result (searching gets you Kurt Suzuki).  This may be a MLB issue, or maybe I just don't know what I'm doing, but figured I'd let someone more familiar with the APis and JSON etc take a look.  Thanks so much for the bot, it's been a great source for us on Discord! and thanks in advance for looking to see if I'm stupid or not.

**Comment by CaptainMoustache** [comment]
Interesting, I'll see what I can find out. I'm glad yo hear you're enjoying basebot!

**Comment by CaptainMoustache** [comment]
I tried a couple different queries directly to the MLB api and the only thing that returns results is "Suzuki" and like you observed it's just Kurt Suzuki

`{
    "search_player_all": {
        "copyRight": " Copyright 2022 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt  ",
        "queryResults": {
            "created": "2022-04-26T03:15:15",
            "totalSize": "1",
            "row": {
                "position": "C",
                "birth_country": "USA",
                "weight": "210",
                "birth_state": "HI",
                "name_display_first_last": "Kurt Suzuki",
                "college": "Cal State Fullerton",
                "height_inches": "11",
                "name_display_roster": "Suzuki",
                "sport_code": "mlb",
                "bats": "R",
                "name_first": "Kurt",
                "team_code": "ana",
                "birth_city": "Wailuku",
                "height_feet": "5",
                "pro_debut_date": "2007-06-12T00:00:00",
                "team_full": "Los Angeles Angels",
                "team_abbrev": "LAA",
                "birth_date": "1983-10-04T00:00:00",
                "throws": "R",
                "league": "AL",
                "name_display_last_first": "Suzuki, Kurt",
                "position_id": "2",
                "high_school": "Henry Perrine Baldwin, Wailuku, HI",
                "name_use": "Kurt",
                "player_id": "435559",
                "name_last": "Suzuki",
                "team_id": "108",
                "service_years": "",
                "active_sw": "Y"
            }
        }
    }
}`

Short of changing the player lookup to a different service I can't do anything about this at the moment

**Comment by CaptainMoustache** [comment]
Closing as won't fix
