### ISSUE TITLE
Reset listening permissions?

### ISSUE THREAD

**Issue by jordanimal** [CaptainMoustache/basebot#4]
Instructed the bot to ignore the only channel it was listening in and now I seem to have no way to communicate with it. Any way to fix?

**Comment by CaptainMoustache** [comment]
What is the name of your server? I'll reset it.

**Comment by jordanimal** [comment]
Midwest Powers League

**Comment by jordanimal** [comment]
Please let me know when you reset it so I can try it again. Thanks so much!
