### ISSUE TITLE
If you make the Bot not listen to the only channel it was assigned to, you can't reassign it to another channel

### ISSUE THREAD

**Issue by TheRedGear** [CaptainMoustache/basebot#5]
I made the bot not listen to the only channel that is was reading commands from and now I can no longer summon the bot to move it to a different channel. I've kicked it from the server and added it and the problem still persisted. 

Is there any way to summon the bot in a different channel at this point? Or is this a bug?

**Comment by CaptainMoustache** [comment]
This is a bug, thanks for reporting it. Please send me your server name and I will fix it for you.

**Comment by TheRedGear** [comment]
> This is a bug, thanks for reporting it. Please send me your server name and I will fix it for you.

Appreciate the quick response! I've provided all the information below.

Server Name:【⚾】MLB Discord
Invite Link: https://discord.gg/NTbrZCn (If you need it)
Preferred Channel for Temp Use: #▌bot-creation (ID: 496537735926906881)

If there is anything else you need from me, please feel free to message me.

**Comment by CaptainMoustache** [comment]
The bot should be reset for your server. Issue has been resolved in ed7ca46aa7b9b1161f990373e326eb955f26a3f5. Thanks again for the report.
