### ISSUE TITLE
"player" command for position players not returning stats

### ISSUE THREAD

**Issue by CaptainMoustache** [CaptainMoustache/basebot#6]

**Comment by Dionysios5** [comment]
Thank you brotha

**Comment by CaptainMoustache** [comment]
[The MLB API endpoint for season hitting stats](https://appac.github.io/mlb-data-api-docs/#stats-data-season-hitting-stats-get) is currently returning an AccessDenied response. Looks like the rest of the endpoints are working so I'm not sure whats going on

**Comment by CaptainMoustache** [comment]
I'm working on a fix for this, but it will likely take a few days to rewrite the player lookup function.

**Comment by Dionysios5** [comment]
Sounds good brotha please let me know when fixed

**Comment by CaptainMoustache** [comment]
This has been temporarily fixed in https://github.com/CaptainMoustache/basebot/commit/a799ecfcfdfc90ecafa12f7a7b38a4e5259dc39a.
This may still be broken for players traded mid-season though.
