### ISSUE TITLE
Not responding to any commands

### ISSUE THREAD

**Issue by The-Dreamz** [CaptainMoustache/basebot#7]
Since this afternoon, no command has worked with the bot to retrieve scores or anything. Any ideas?

**Comment by CaptainMoustache** [comment]
I noticed the scores command not working earlier too, but it seems to be working now. Are you still having issues?

**Comment by The-Dreamz** [comment]
> I noticed the scores command not working earlier too, but it seems to be working now. Are you still having issues?

Hey, I apologize for not getting back sooner. Yes, it has been working! 

I do have a question though regarding the stats provided - is there a way to potentially swap out a couple stats to be replaced by any others?

**Comment by CaptainMoustache** [comment]
It's currently not configurable. I do have a plan to add an expanded stats option that will allow you to see most if not all available stats after looking a player up

**Comment by The-Dreamz** [comment]
> It's currently not configurable. I do have a plan to add an expanded stats option that will allow you to see most if not all available stats after looking a player up

One more question for ya! lol. How far back do stats for players go? As in, is there a cutoff year for when the bot won't recall stats? I was looking - just to test it - Barry Bonds and others stats from like 2003 and it says there were none.

**Comment by CaptainMoustache** [comment]
The MLB api goes back as far as 1900, but in order to fix https://github.com/CaptainMoustache/basebot/issues/6 I had to make a change that disabled the year specific stats for hitting. However it still works for pitching stats. I'll look into a workaround for it.
